name: 'Compile Examples'
author: 'Zachary J. Fields'
description: 'Validate examples by compiling for supported platforms'
runs:
  using: 'docker'
  image: './Dockerfile'
  entrypoint: 'bash'
  args:
    - -c
    - "HOME=/root arduino-cli compile \
      --build-property compiler.cpp.extra_flags='-Wno-unused-parameter -Werror' \
      --fqbn ${{ inputs.fully-qualified-board-name }} \
      --warnings all \
      ${{ inputs.example-sketch }}"
