# publishes the coveralls report to coveralls.io
# Requires COVERALLS_REPO_TOKEN environment variable to contain the access token generated by coveralls.

result = 0
if [ -f coverage.json ]; then 
    python3 .github/actions/publish-coverage/report/report.py coverage.json
    if [ 0 -ne $? ]; then
        echo "Unable to publish coverage report!"
        result = 1
    fi
else
    echo "File coverage.json does not exist"
    result = 2
fi
exit $result
