name: Build and Test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'


jobs:
  coverage:
    name: coverage (ubuntu-18.04)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov g++ valgrind
      - name: test
        run: ./test/run_all_tests.sh
      - name: remove test source coverage
        run: rm *mock*.gc?? *Mock*.gc?? *test*.gc??
      - name: run lcov
        run: lcov --capture --directory . --output-file lcov.info
      - name: Version Check
        id: ver
        run: |
          gcov --version
          lcov --version
          ls -al ./lcov.info
          cat ./lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"

