name: Note Arduino Build Examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_examples:
    # ensure that only one job is run at once so the docker container is first built
    concurrency: 
      group: ${{ github.head_ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platforms: "esp32:esp32"
            boards: "esp32:esp32:featheresp32"
            source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json      
          - platforms: "arduino:avr"
            boards: "arduino:avr:uno"
          - platforms: "arduino:mbed_rp2040"
            boards: "arduino:mbed_rp2040:pico"
          # - platforms: "adafruit:nrf52"
          #   boards: "adafruit:nrf52:feather52840"
          #   source-url: https://www.adafruit.com/package_adafruit_index.json
          - platforms: "STMicroelectronics:stm32"
            boards: "STMicroelectronics:stm32:Disco"
            source-url: "https://github.com/stm32duino/BoardManagerFiles/raw/master/package_stmicroelectronics_index.json"
            
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build library examples
        id: build_examples
        uses: ./.github/actions/build-examples
        env:
          BOARDS: ${{ matrix.boards }}
          PLATFORMS: ${{ matrix.platforms }}
          EXTRA_FLAGS: ${{ matrix.extra_compile_flags }}
    
